Add missing headers argument in old downloaders
This fixes `TypeError: DownloadSession.get_filesize() missing 1 required positional argument: 'headers'` which was changed in commit e082e6e630fdb599a73c08356e503e5b8f3796ba